version: "0.1"
services:
  app:
    build:
      args:
        user: andreeve
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: altertravel_img
    container_name: altertravel_container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - altertravel

  nginx:
    image: nginx:alpine
    container_name: altertravel
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - altertravel

networks:
  altertravel:
    driver: bridge